baseURL = "http://example.org/"
languageCode = "en-us"
title = "Deanlab"

enableGitInfo = true

[params]
    email = "brendan@thesimplekid.com"
    google_scholar = "z3z-PV8AAAAJ&hl"
    copyright = "© Deanlab 2021"